### ISSUE TITLE
[Bug Report]: Game test issue #1 (via: Game Design)

### ISSUE THREAD

**Issue by beersanp** [khonsaiinc/aquamarine#34]
Build: 19022023

**ปัญหาที่เกิดขึ้น**
- จอยไม่ติด
- ใช้เมาส์เลือกไม่ได้คำตอบไม่ได้
- กลับเข้าห้องมาใหม่คนมาส่งของซ้ำ
- เดินทะลุฉากในห้องได้
- ปุ่มenteracกับปุ้มคุยคนละปุ่มกันมันควรจะเป็นปุ้มเดียวกัน

**Task**

- [x] จอยไม่ติด
- [x] ใช้เมาส์เลือกไม่ได้คำตอบไม่ได้
- [x] กลับเข้าห้องมาใหม่คนมาส่งของซ้ำ
- [x] เดินทะลุฉากในห้องได้
- [x] ปุ่มenteracกับปุ้มคุยคนละปุ่มกันมันควรจะเป็นปุ้มเดียวกัน

**Comment by beersanp** [comment]
thanks, game design!

จะตอบโดยเรียงปัญหาตามที่เจอเรียงข้อนะ
- จอยไม่ติด
- ปุ่ม enteract กับปุ่มคุยคนละปุ่มกันมันควรจะเป็นปุ่มเดียวกัน
> - โอเค ข้อแรกปัญหาของ controller เดี๋ยวจะเพิ่มฝั่ง dualsense ให้ ตอนนี้เราแมพจอยอีกแบบอยู่ เดี๋ยวจะแก้ให้เร็วที่สุด
> - ส่วนปุ่มเดี๋ยว เดี๋ยวเราหาวิธีแก้ให้ไวที่สุด
> @roon2555 ไอส่วนจอยนี่ เราจะแมพให้ แต่ลองเอาจอย ps4 ลองให้หน่อยได้ปะ
- ใช้เมาส์เลือกไม่ได้คำตอบไม่ได้
> เมาส์ใช้ไม่ได้ใช่ไหม ? เราตั้งใจไม่ให้ผู้เล่นกดเมาส์ในเกมส์เลย เนื่องจากมันเป็นเนื้อเรื่องเพียวๆตามนายได้ออกแบบไว้ แต่หลักๆจะใช้ kb กดก่อน มีระหว่าง 
```
"Arrow" or "WASD" เป็นการเดิน
"E" เป็น Interact
"Spacebar" เป็นการอ่านข้อความต่อไปเรื่อยๆ
```
- กลับเข้าห้องมาใหม่คนมาส่งของซ้ำ
- เดินทะลุฉากในห้องได้
> ยังไม่ได้ทำเช็คว่าเราได้ของแล้ว เมื่อวานเรา build แต่เทสให้ instructor ดูเฉยๆ เดี๋ยวจะใส่ให้ใน week นี้ 
> @GGameover303 ฝากด้วยครับเพ่

**Comment by beersanp** [comment]
- ปุ่ม enteract กับปุ่มคุยคนละปุ่มกันมันควรจะเป็นปุ่มเดียวกัน
> คิดว่ามันไม่น่าจะทำได้นะ แต่เดี๋ยวหาข้อมูลเพิ่มเติมก่อน ปกติแล้วเกมส์ที่มันมีการอ่านเนื้อเรื่องแบบง่ายที่สุด บางทีอาจจะไม่ได้ตั้งให้ใช้ปุ่มเดียวกันเป็นหลัก
> ทาง dev ปกติแล้วถ้าเอา input ที่ปุ่มซ้ำกันไปวางมันจะเป็นการสั่งการทำงาน 2 รอบในการกดปุ่ม 1 ครั้ง เดี๋ยวขอ research ก่อน

**Comment by beersanp** [comment]
-  จอยไม่ติด

> เราเจอ list จอยที่ใช้ได้สำหรับตอนนี้ละ @roon2555 ลองฝากสลับมาเอา dualsense เช็คให้หน่อย

หรือว่าเราต้องทำ DirectInput ?

![Image](https://github.com/khonsaiinc/aquamarine/assets/152690133/fe0022d1-864d-487b-ae98-81e889d23c74)

**Comment by beersanp** [comment]
[16:46] via NO5TALGI4:
comment test build
ของวันที่ 22/02/2024

- ออกจากร้านซุปเปอร์ไม่ได้
- ตอนเปิดประตูแล้วมีคัตซีนแนะนำให้คัตซีนขึ้นก่อนแล้วค่อยให้ประตูเปิด(หลังคัตซีนจบประตูจะเปิดอยู่เลย)
- ตอนออกนอกห้องมันยังมีคัตซีนคนส่งของติดมาด้วย
- ตอนคุยจบมันจะมีช่องสนทนาเปล่าขึ้นมาอันนี้ถ้าเราคุยเส็จช่องคุยก็ควรจะหายไปเลยไม่ควรที่จะมีช่องเปล่าขึ้นมา
- หลังจากเราคุยกับรุ่นพี่เส็จรุ่นพี่ควรจะเดินออกจาฉากไปหรือไม่ก็เฟดหายไปเลยไม่ควรจะคืนอยู่ที่เดิม
- คัตซีนเดินไปทำงานตอนออกจากห้องมันแปลกๆไปหน่อย ควรใส่กลางๆทางหรือไม่ก็ใส่ตอนใกล้ถึงแต่ถ้าคิดว่าทางมันใกล้เกินไปก็ยืดฉากออกไปหน่อย(ถ้าทำได้)หรือไม่ก็เอาออกไปเลยเพราะตอนที่ดูคัตซีน ดูแล้วรู้สึกงงๆไม่รู้ว่ตัวเรากำลังทำอะไรอยู่

ปัญหาเก่า

- เรื่องจอยจริงๆเกมนี้เราไม่ได้ตั้งใจจะให้ใช้จอยได้นะ เพราะงั้นถ้ามีปัญหาเรื่องจอยให้แก้หลังสุด
- เรื่องเม้าเนื่องจากตอนเล่นเคอเซอร์เมาท์มันลอยอยู่หน้าจอเกม ถ้าเกมที่ไม่ได้ใช้เมาท์มันควรจะไม่มีเมาท์ตอนที่เราเล่นเกมอยู่ หากตอนเล่นเกม
เคอเซอร์เมาท์ยังคงปรากฏบนหน้าจอเกมเมาก็ควรที่จะกดได้

**Comment by beersanp** [comment]
ตอบอันนี้ก่อน
> - เรื่องจอยจริงๆเกมนี้เราไม่ได้ตั้งใจจะให้ใช้จอยได้นะ เพราะงั้นถ้ามีปัญหาเรื่องจอยให้แก้หลังสุด
> - เรื่องเม้าเนื่องจากตอนเล่นเคอเซอร์เมาท์มันลอยอยู่หน้าจอเกม ถ้าเกมที่ไม่ได้ใช้เมาท์มันควรจะไม่มีเมาท์ตอนที่เราเล่นเกมอยู่ หากตอนเล่นเกม
เคอเซอร์เมาท์ยังคงปรากฏบนหน้าจอเกมเมาก็ควรที่จะกดได้

เดี๋ยวเปิดเมาส์ให้ ง่ายนิดเดียว
น่าจะทำเปิดหมดเลย แต่จะ priority อย่างอื่นไว้ทีหลัง

**Comment by beersanp** [comment]
แก้หมดละ thanks https://github.com/khonsaiinc/aquamarine/commit/eb71b22ca21e96e806096186d51a30a855473203
